openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API for purchasing order and performing transaction

paths:
  /payment-service/api/payment:
    post:
      tags:
        - Payment
      operationId: perform payment
      summary: Perform payment transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          $ref: '#/components/responses/Transaction200Response'
        default:
          $ref: '#/components/responses/GenericDefaultResponse'


components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        detail:
          type: string
        reason:
          type: string
      required:
        - name
        - code
        - detail

    PaymentRequest:
      type: object
      properties:
        receiptId:
          type: integer
          format: int32
        studentId:
          type: integer
          format: int32
        grade:
          type: string
        amount:
          type: number
          format: double
        studentName:
          type: string
        feeName:
          type: string
        cardNumber:
          type: string
        cardType:
          type: string
      required:
        - studentId
        - grade
        - feeType
        - quantity

    OrderResponse:
      allOf:
        - $ref: '#/components/schemas/PaymentRequest'
        - type: object
          properties:
            feeId:
              type: integer
              format: int32
              readOnly: true
    Transaction200Response:
      type: object
      properties:
        referenceNumber:
          type: integer
          format: int32
        status:
          type: string
      required:
        - referenceNumber
        - status


  responses:
    Transaction200Response:
      description: Transaction performed sucessfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction200Response'
    Generic404Response:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    GenericDefaultResponse:
      description: This is the default internal server error. System was not able to process this request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'